name: Deploy Theme to Test Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploying via SFTP
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./shift-theme/
        server-dir: /public_html/test/wp-content/themes/SureShiftWebsiteRedesigned/sureshift-theme/